
theme: jekyll-theme-cayman

title: National Microbiology Laboratory Genomics and Bioinformatics Training Material 
description: This is an example webpage for a training based website that can be used to share resources externally
